version: '3.8'
services:
  ##################
  #  SERVICES
  ##################


  ##################
  #  DATABASES
  ##################

  coin_market_cap_postgres:
    container_name: coin_market_cap_postgres
    hostname: coin_market_cap_postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - coin_market_cap_postgres_data:/var/lib/postgresql/data

volumes:
  coin_market_cap_postgres_data: